#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))

    if(d > n):
        d = d % n
    arr = []
    for i in range(d, n):
        arr.append(a[i])
    for x in range(d):
        arr.append(a[x])
    for y in arr:
        print(y, end = " ")
